[tool.ruff]
# Minimum version to assume for error checking
target-version = "py39"

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
#select = ["E4", "E7", "E9", "F"]
select = ["ALL"]
ignore = [
    "ANN001",
    "ANN201",
    "COM812",
    "D103",
    "D211",
    "D213",
    "E501",
    "EM102",
    "ISC001",
    "PLR0913",
    "S101",
    "T201",
    "TRY003",
]
